# Generated by Django 5.0.1 on 2024-02-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_chargingspot_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
